name: Feature Request
description: Suggest a new feature or enhancement for jaybird
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea below.

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What type of feature are you requesting?
      options:
        - New station/stream support
        - Audio playback features
        - Discord Rich Presence improvements
        - UI/display improvements
        - Controls and keyboard shortcuts
        - Configuration options
        - Platform-specific feature
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? If so, please describe it.
      placeholder: "I'm frustrated when... / It would be helpful if..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or enhancement you'd like to see
      placeholder: What would you like to happen?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions you've thought of
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature be used? What's the intended workflow?
      placeholder: |
        1. User opens jaybird
        2. User presses new hotkey
        3. Feature activates and...
    validations:
      required: false

  - type: checkboxes
    id: platforms
    attributes:
      label: Target Platforms
      description: Which platforms should this feature support?
      options:
        - label: Windows
        - label: macOS
        - label: Linux
        - label: All platforms

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to implementing this feature?
      options:
        - label: I'd like to work on this feature myself
        - label: I can help test this feature
