name: Submit to Winget

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to submit (e.g., 1.0.0 - without v prefix)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  submit-to-winget:
    runs-on: windows-latest
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'release' && github.event.action == 'published')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get version
      id: get_version
      run: |
        if ("${{ github.event_name }}" -eq "workflow_dispatch") {
          $version = "${{ github.event.inputs.version }}"
        } else {
          # Strip 'v' prefix from tag name (e.g., v1.0.0 -> 1.0.0)
          $version = "${{ github.ref_name }}" -replace '^v', ''
        }
        echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        Write-Host "Version: $version"
      shell: pwsh

    - name: Download Windows release asset
      run: |
        $version = "${{ steps.get_version.outputs.VERSION }}"
        $tagName = "v$version"
        $baseUrl = "https://github.com/${{ github.repository }}/releases/download/$tagName"

        Write-Host "Downloading from: $baseUrl"

        # Download Windows x64 zip and hash
        try {
          Invoke-WebRequest -Uri "$baseUrl/jaybird-$tagName-win-x64.zip" -OutFile "jaybird-win-x64.zip"
          Write-Host "✅ Downloaded jaybird-$tagName-win-x64.zip"
        } catch {
          Write-Host "❌ Failed to download Windows x64 zip"
          Write-Host "URL: $baseUrl/jaybird-$tagName-win-x64.zip"
          exit 1
        }

        try {
          Invoke-WebRequest -Uri "$baseUrl/jaybird-$tagName-win-x64.zip.sha256" -OutFile "jaybird-win-x64.zip.sha256"
          Write-Host "✅ Downloaded hash file"
        } catch {
          Write-Host "❌ Failed to download hash file"
          Write-Host "URL: $baseUrl/jaybird-$tagName-win-x64.zip.sha256"
          exit 1
        }
      shell: pwsh

    - name: Extract SHA256 hash
      id: get_hash
      run: |
        # Read hash file and extract just the hash (first part before space)
        $hashContent = Get-Content "jaybird-win-x64.zip.sha256" -Raw
        $sha256 = ($hashContent -split '\s+')[0]

        Write-Host "SHA256: $sha256"
        echo "SHA256=$sha256" >> $env:GITHUB_OUTPUT

        # Validate hash format (should be 64 hex characters)
        if ($sha256 -notmatch '^[a-fA-F0-9]{64}$') {
          Write-Host "❌ Invalid SHA256 hash format: $sha256"
          exit 1
        }
      shell: pwsh

    - name: Prepare manifests from templates
      run: |
        $version = "${{ steps.get_version.outputs.VERSION }}"
        $tagName = "v$version"
        $sha256 = "${{ steps.get_hash.outputs.SHA256 }}"
        $installerUrl = "https://github.com/${{ github.repository }}/releases/download/$tagName/jaybird-$tagName-win-x64.zip"

        Write-Host "Preparing manifests for version $version"
        Write-Host "Installer URL: $installerUrl"
        Write-Host "SHA256: $sha256"

        # Create output directory structure
        $manifestDir = "manifests/u/uncleLukie/jaybird/$version"
        New-Item -ItemType Directory -Path $manifestDir -Force | Out-Null

        # Copy and update version manifest
        $versionManifest = Get-Content "winget-manifests/uncleLukie.jaybird.yaml" -Raw
        $versionManifest = $versionManifest -replace 'PackageVersion: [\d\.]+', "PackageVersion: $version"
        $versionManifest | Set-Content "$manifestDir/uncleLukie.jaybird.yaml" -Encoding UTF8

        # Copy and update locale manifest
        $localeManifest = Get-Content "winget-manifests/uncleLukie.jaybird.locale.en-US.yaml" -Raw
        $localeManifest = $localeManifest -replace 'PackageVersion: [\d\.]+', "PackageVersion: $version"
        $localeManifest = $localeManifest -replace 'ReleaseNotesUrl: .*', "ReleaseNotesUrl: https://github.com/${{ github.repository }}/releases/tag/$tagName"
        $localeManifest | Set-Content "$manifestDir/uncleLukie.jaybird.locale.en-US.yaml" -Encoding UTF8

        # Copy and update installer manifest
        $installerManifest = Get-Content "winget-manifests/uncleLukie.jaybird.installer.yaml" -Raw
        $installerManifest = $installerManifest -replace 'PackageVersion: [\d\.]+', "PackageVersion: $version"
        $installerManifest = $installerManifest -replace 'InstallerUrl: .*', "InstallerUrl: $installerUrl"
        $installerManifest = $installerManifest -replace 'InstallerSha256: .*', "InstallerSha256: $sha256"
        $installerManifest | Set-Content "$manifestDir/uncleLukie.jaybird.installer.yaml" -Encoding UTF8

        Write-Host "✅ Manifests prepared in $manifestDir"
      shell: pwsh

    - name: Install WingetCreate
      run: |
        Write-Host "Installing WingetCreate..."
        winget install wingetcreate --accept-source-agreements --accept-package-agreements

        # Verify installation
        $wingetcreatePath = (Get-Command wingetcreate -ErrorAction SilentlyContinue).Source
        if ($wingetcreatePath) {
          Write-Host "✅ WingetCreate installed at: $wingetcreatePath"
        } else {
          Write-Host "❌ WingetCreate installation failed"
          exit 1
        }
      shell: pwsh

    - name: Validate Manifests
      run: |
        $version = "${{ steps.get_version.outputs.VERSION }}"
        Write-Host "Validating manifests..."

        wingetcreate validate "manifests/u/uncleLukie/jaybird/$version"

        if ($LASTEXITCODE -ne 0) {
          Write-Host "❌ Manifest validation failed"
          exit 1
        }

        Write-Host "✅ Manifest validation passed"
      shell: pwsh

    - name: Display Generated Manifests
      run: |
        $version = "${{ steps.get_version.outputs.VERSION }}"
        Write-Host "`n📁 Generated manifest files:"
        Get-ChildItem -Path "manifests/u/uncleLukie/jaybird/$version" -File | ForEach-Object {
          Write-Host "`n=== $($_.Name) ==="
          Get-Content $_.FullName
        }
      shell: pwsh

    - name: Submit to Winget (if token provided)
      run: |
        $version = "${{ steps.get_version.outputs.VERSION }}"
        $token = "${{ secrets.WINGET_GITHUB_TOKEN }}"

        if ([string]::IsNullOrEmpty($token)) {
          Write-Host "⚠️  WINGET_GITHUB_TOKEN not found - skipping automatic submission"
          Write-Host "Manifests have been uploaded as artifacts for manual submission"
          exit 0
        }

        Write-Host "📤 Submitting to winget-pkgs repository..."

        wingetcreate submit `
          --token $token `
          "manifests/u/uncleLukie/jaybird/$version"

        if ($LASTEXITCODE -eq 0) {
          Write-Host "✅ Successfully submitted to winget-pkgs!"
          Write-Host "🔗 Track your PR at: https://github.com/microsoft/winget-pkgs/pulls"
        } else {
          Write-Host "❌ Submission failed"
          exit 1
        }
      shell: pwsh

    - name: Upload Manifest as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: winget-manifest-${{ steps.get_version.outputs.VERSION }}
        path: manifests/
        retention-days: 90

    - name: Summary
      run: |
        $version = "${{ steps.get_version.outputs.VERSION }}"

        Write-Host "`n✅ Winget submission workflow completed!"
        Write-Host "Version: $version"
        Write-Host "Manifests uploaded as artifact: winget-manifest-$version"

        if ("${{ secrets.WINGET_GITHUB_TOKEN }}" -eq "") {
          Write-Host "`n⚠️  No WINGET_GITHUB_TOKEN found - manifests were not submitted"
          Write-Host "To enable automatic submission:"
          Write-Host "1. Create a GitHub Personal Access Token with 'public_repo' scope"
          Write-Host "2. Add it as a repository secret named 'WINGET_GITHUB_TOKEN'"
          Write-Host "`nOr submit manually:"
          Write-Host "1. Download the manifest artifact"
          Write-Host "2. Fork microsoft/winget-pkgs"
          Write-Host "3. Copy manifests to the correct directory"
          Write-Host "4. Create a pull request"
        }
      shell: pwsh
